name: redstone_mapper
version: 0.1.0
author: Luiz Mineo <luiz.mineo@gmail.com>
description: A mapper plugin for Redstone.dart
homepage: http://luizmineo.github.io/redstone.dart
environment:
  sdk: '>=1.4.0 <2.0.0'
dependencies:
  redstone: '>= 0.5.4 < 0.6.0'
  analyzer: '>=0.13.0 <0.14.0'
  barback: '>=0.13.0 <0.14.0'
  code_transformers: '>=0.1.3 <0.2.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.12.0'
