name: redstone_mapper
version: 0.1.7
author: Luiz Mineo <luiz.mineo@gmail.com>
description: A mapper plugin for Redstone.dart 
homepage: http://redstonedart.org
environment:
  sdk: '>=1.4.0 <2.0.0'
dependencies:
  redstone: '>=0.5.10 <0.6.0'
  analyzer: '>=0.15.0 <0.19.0'
  code_transformers: '>=0.1.6 <0.3.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.12.0'
transformers:
  - redstone_mapper
